customhost = "testdb.crtzsv04f16b.us-east-1.rds.amazonaws.com"
customuser = "testdb"
custompass = "testtest123"
customdb = "chan"
custombucket = "addemployee-to-store-data"
customregion = "us-east-1"
